version: '2.2'
services:
  app:
    build:
      context: ../
      dockerfile: ./Dockerfile
    environment:
      - APM_SERVER_PATH=http://apm-server:8200
    ports:
      - "3000:3000"
    networks:
      elastic-network:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      elastic-network:

  kibana:
    image: docker.elastic.co/kibana/kibana:7.3.1
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "5601:5601"
    networks:
      elastic-network:

  apm-server:
    image: docker.elastic.co/apm/apm-server:7.3.1
    volumes:
      - ./apm-server/apm-server.yml:/usr/share/apm-server/apm-server.yml
    ports:
      - "8200:8200"
    user: apm-server
    command: --strict.perms=false -e
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
    networks:
      elastic-network:

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.3.1
    environment:
      - setup.kibana.host=kibana:5601
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      - APP_HOST=app.id
    command: --strict.perms=false -e
    user: root
    volumes:
      - ./filebeat/config/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      elastic-network:

networks:
  elastic-network:
